// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0l2_ksLUjqDg8Hl6GSORigKGczI3_C_w',
    appId: '1:117652060349:web:253c44545313cfdcc5dfd4',
    messagingSenderId: '117652060349',
    projectId: 'assessment-3d660',
    authDomain: 'assessment-3d660.firebaseapp.com',
    storageBucket: 'assessment-3d660.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf60TJt_jSFe_tAhK2f7JJ0Tf1TEXYqDw',
    appId: '1:117652060349:android:908d526737783af9c5dfd4',
    messagingSenderId: '117652060349',
    projectId: 'assessment-3d660',
    storageBucket: 'assessment-3d660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkY-PzCFUJyvqSy2LzprNUTiZvxP_wgfg',
    appId: '1:117652060349:ios:1bedfeeed1e0ebc9c5dfd4',
    messagingSenderId: '117652060349',
    projectId: 'assessment-3d660',
    storageBucket: 'assessment-3d660.appspot.com',
    iosBundleId: 'com.sulaiman.assessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkY-PzCFUJyvqSy2LzprNUTiZvxP_wgfg',
    appId: '1:117652060349:ios:ea981292336b67afc5dfd4',
    messagingSenderId: '117652060349',
    projectId: 'assessment-3d660',
    storageBucket: 'assessment-3d660.appspot.com',
    iosBundleId: 'com.sulaiman.assessment.RunnerTests',
  );
}
